# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cca2697dc263e2eb30006289bcf769c62e6f63d347f407126248fbbdf1468f62bc6e4de2f9ba0275eedab3d77a1a49ebe02f9f7ba110de504a3cd263e21efa4e

test:
  secret_key_base: 01ab5ef69f1e9559f4cce89b5349f1128a5928632c78dd07dfbb2f0b3934651fe1ce5f003a5a1887ad59d8eb4e4421bc2a0d9bead7010753d4e06b20630061fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
